#.travis.yml
dist: trusty
language: node_js
node_js:
  - "8.1.4"

branches:
  only:
    - dev
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# to run components unit tests with chrome
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install
  - npm install -g npx

script:
  - npx nuxt build
  - npx karma start test/unit/karma.conf.js

notifications:
  email:
    on_failure: change
    on_success: change
